### ISSUE TITLE
Experience Tracker Feature

### ISSUE THREAD

**Issue by robertwayne** [robertwayne/petrock#16]
- [ ] Implement base algorithm, tracking, and page design.
- [ ] Auto-save to local storage. Prevents disconnects, reloads, or whatever from messing up tracking.
- [ ] Have a restart session button that wipes the current session, save automatically on updates.
- [ ] Low duration sessions are very erratic with xp/hr but there's really no way to fix that. Just add a warning that <15 min sessions are not very accurate. Limitation of 5 minute DB saves for the game. 
- [ ] Allow save session to DB for duration >30 min. This would let people track other players' xp, but tbf it's all public data so if someone wants to do it, they can. Would be silly to deal with a whole auth scheme unless the data goes private (which it never will for the leaderboards).
- [ ] Add log for each update with a differential to last update (green + / red -) and times
